version: '2'

services:
  database:
    environment:
      - "MYSQL_ROOT_PASSWORD=moodle"
      - "MYSQL_DATABASE=moodle"
      - "MYSQL_USER=moodle"
      - "MYSQL_PASSWORD=moodle"
    image: mysql:8.0.19
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
  moodle:
    build: ./
    depends_on:
      - database
    links:
      - database:moodle-database
    ports:
      - "80:80"
    volumes:
      - ./testfs/moodledata:/moodle/data
      - ./testfs/moodle-config.php:/var/www/html/config.php:ro
