version: '2'

services:
  database:
    environment:
      - "MYSQL_ROOT_PASSWORD=moodle"
      - "MYSQL_DATABASE=moodle"
      - "MYSQL_USER=moodle"
      - "MYSQL_PASSWORD=moodle"
    image: mysql:8.0.19
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
  moodle:
    build: ./
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=moodle
      - DB_USERNAME=moodle
      - DB_PASSWORD=moodle
      - DOMAIN_URL=http://localhost
    links:
      - database:moodle-database
    ports:
      - "80:80"
    volumes:
      - ./docker/moodledata:/moodle/data