version: '2'

services:
  database:
    environment:
      - "ROOT_PASSWORD=moodle"
      - "POSTGRES_DATABASE=moodle"
      - "POSTGRES_USER=moodle"
      - "POSTGRES_PASSWORD=moodle"
    image: postgres:9.6-alpine
    ports:
      - "5432"
  moodle:
    build: ./
    depends_on:
      - database
    links:
      - database:moodle-database
    ports:
      - "80:80"
    volumes:
      - ./testfs/moodledata:/moodle/data
      - ./testfs/moodle-config.php:/var/www/html/config.php:ro
