apiVersion: v1
kind: Service
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  ports:
    - nodePort: 31337
      port: 80
      targetPort: 80
  selector:
    app: moodle
    tier: frontend
  type: NodePort
